from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from numpy import pi

qreg_q = QuantumRegister(2, 'q')
creg_c = ClassicalRegister(2, 'c')
circuit = QuantumCircuit(qreg_q, creg_c)

circuit.x(qreg_q[0])
circuit.u3(-pi, 0, 0, qreg_q[0])
circuit.x(qreg_q[1])
circuit.rz(pi/2, qreg_q[0])
circuit.u3(pi, 0, 0, qreg_q[1])
circuit.barrier(qreg_q[0])
circuit.rz(pi/2, qreg_q[1])
circuit.h(qreg_q[0])
circuit.barrier(qreg_q[1])
circuit.rz(pi/2, qreg_q[0])
circuit.h(qreg_q[1])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.barrier(qreg_q[0])
circuit.barrier(qreg_q[1])
circuit.u3(0, -pi/2, 0, qreg_q[0])
circuit.u3(0, -pi, 0, qreg_q[1])
circuit.barrier(qreg_q[0])
circuit.barrier(qreg_q[1])
circuit.h(qreg_q[0])
circuit.h(qreg_q[1])
circuit.rz(pi/2, qreg_q[0])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.barrier(qreg_q[0])
circuit.barrier(qreg_q[1])
circuit.u3(pi/2, pi, 0, qreg_q[0])
circuit.u3(-pi/2, -pi, 0, qreg_q[1])
circuit.barrier(qreg_q[0])
circuit.barrier(qreg_q[1])
circuit.h(qreg_q[0])
circuit.h(qreg_q[1])
circuit.rz(pi/2, qreg_q[0])
circuit.cx(qreg_q[0], qreg_q[1])
circuit.barrier(qreg_q[0])
circuit.barrier(qreg_q[1])
circuit.u3(pi, 0, 0, qreg_q[0])
circuit.u3(-pi, 0, 0, qreg_q[1])
circuit.rz(-pi/2, qreg_q[0])
circuit.rz(pi/2, qreg_q[1])
circuit.measure(qreg_q[0], creg_c[0])
circuit.measure(qreg_q[1], creg_c[1])